services:
    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: foodiDB
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3310:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
